"use client"

import React from 'react'
import Link from 'next/link'

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <h1 className="text-4xl font-bold text-foreground mb-4">About MyAgriScan</h1>

      <p className="text-lg text-muted-foreground mb-6">
        MyAgriScan helps farmers quickly identify plant diseases from a single photo and
        provides short, practical treatment and prevention advice generated by an expert AI.
        The site combines a lightweight image classifier running in a FastAPI backend with
        a server-side generative model that produces farmer-friendly recommendations.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">How it solves the problem</h2>
        <ul className="list-disc ml-6 space-y-2 text-muted-foreground">
          <li>
            Quick detection: Upload a clear photo of a leaf and the system returns a probable diagnosis within seconds.
          </li>
          <li>
            Practical advice: After classification the site requests short, actionable guidance (prevention, treatment, tips) from a generative model, formatted for farmers.
          </li>
          <li>
            Safe deployment: The image model uses weights saved as a state dict to avoid unsafe pickled objects, and the generative API key is kept server-side so it is never exposed to users.
          </li>
          <li>
            Fault-tolerant flow: If the generative service is unavailable the classifier still returns a result so farmers can make decisions without blocking.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">How it works (technical overview)</h2>
        <ol className="list-decimal ml-6 space-y-2 text-muted-foreground">
          <li>
            The frontend uploads the image to a Next.js API route which proxies the file to a FastAPI classifier.
          </li>
          <li>
            FastAPI runs a PyTorch model (ResNet9) on the image and returns the top prediction and confidence.
          </li>
          <li>
            The frontend calls a separate Next.js server route which asks a generative model (server-side) for short structured advice about the predicted disease.
          </li>
          <li>
            The frontend displays both the classification and the parsed advice (prevention, treatment, tips). If the generative step fails, the UI still shows the classification and a friendly message.
          </li>
        </ol>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">Step-by-step: How farmers can use this site</h2>
        <ol className="list-decimal ml-6 space-y-3 text-muted-foreground">
          <li>
            Take a clear photo of the affected leaf (good lighting, close-up of spots or symptoms).
          </li>
          <li>
            Open the Diagnose page and upload the photo using the "Analyze" button.
          </li>
          <li>
            Wait for the classification to finish — you'll see the predicted disease name and confidence score.
          </li>
          <li>
            The site will then fetch short prevention and treatment tips; read these and follow the simple steps recommended.
          </li>
          <li>
            If you're unsure or the confidence is low, save the image to your history and consult a local extension officer with the saved report.
          </li>
        </ol>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-3">Privacy & Safety</h2>
        <p className="text-muted-foreground">
          Uploaded photos are not published publicly. The generative AI key is stored server-side and is never exposed
          to the browser. For production deployments you should add logging, rate-limiting and explicit consent flows before
          collecting large numbers of images.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-3">Need help?</h2>
        <p className="text-muted-foreground mb-4">If you run into issues or want to improve model accuracy, please:</p>
        <ul className="list-disc ml-6 text-muted-foreground">
          <li>Double-check your image quality and retake photos where necessary.</li>
          <li>Contact the project maintainers or your local agricultural extension for region-specific advice.</li>
        </ul>
      </section>

      <div className="mt-8">
        <Link href="/">
          <div className="text-primary font-medium">← Back to Home</div>
        </Link>
      </div>
    </div>
  )
}
